Default implementation of image segmentation using SAM
v-imark/nap-image-segmentation pull request #1
Opened 2024-02-21 09:43 UTC by v-imark

2024-02-21 17:27 UTC, v-imark commented
Default implementation of the segmentation part of the project implemented. Saves the masks in a folder and stores metadata from the output in a csv file.

2024-02-22 08:34 UTC, ResearchDaniel requested changes
I also recommend adding linter and github actions to aid in code formating
https://github.com/pre-commit/pre-commit

2024-02-22 08:34 UTC, ResearchDaniel commented on main.py
> +command = [
Use argparse
https://docs.python.org/3/library/argparse.html

2024-02-22 08:34 UTC, ResearchDaniel commented on main.py
> +subprocess.run(command)
Use `__main__`
https://docs.python.org/3/library/__main__.html#module-__main__

2024-02-22 08:34 UTC, ResearchDaniel commented on main.py
Is the purpose of this file to supply default arguments?
That can be done via argparse

2024-02-22 08:34 UTC, ResearchDaniel commented on segment_images.py
> +parser.add_argument("--sam_model_type", help="First argument")
Add supported options and default arguments to parser args

2024-02-22 08:34 UTC, ResearchDaniel commented on segment_images.py
> +parser.add_argument("--checkpoint", help="Second argument")
Adjust help text

2024-02-22 08:34 UTC, ResearchDaniel commented on segment_images.py
> +    # start_time = time.time()
Remove commented code

2024-02-22 08:34 UTC, ResearchDaniel commented on segment_images.py
> +    print("Segmenting image...")
More informative with name of image

2024-02-22 08:34 UTC, ResearchDaniel commented on segment_images.py
> +    # Todo: exclude small masks
Not part of this function (Single responsibility principle)

2024-02-22 08:34 UTC, ResearchDaniel commented on segment_images.py
> +    for mask in masks:
```suggestion
    for count, mask in enumerate(masks):
```

2024-02-22 08:34 UTC, ResearchDaniel commented on segment_images.py
> +    for mask in masks:
Is count necessary to include?

2024-02-22 08:34 UTC, ResearchDaniel commented on segment_images.py
> +    output_name = f"cifar10_{args.size}"
Add as arguments

2024-02-22 08:34 UTC, ResearchDaniel commented on segment_images.py
> +        if str(img_folder_files[i]).lower().endswith((".png", ".jpg", ".jpeg")):
Use Path.suffix:
https://docs.python.org/3/library/pathlib.html
```suggestion
        if img_folder_files[i].suffix in [".png", ".jpg", ".jpeg"]:
```

2024-02-22 08:34 UTC, ResearchDaniel commented on segmentation.py
> +def register_sam(
Duplicate code

2024-02-22 12:34 UTC, ResearchDaniel commented on .idea/inspectionProfiles/Project_Default.xml
Remove .ideas folder and add to git ignore file

2024-02-22 18:23 UTC, ResearchDaniel approved these changes

2024-02-22 18:23 UTC, ResearchDaniel commented on segment_images.py
> +    print(f"Segmenting image {name}...")
Would move this to the calling side. Unnecessary to specify name just for printing

2024-02-23 11:14 UTC, merged